services:
  postgres:
    image: 'postgres:17.3'
    environment:
      - 'POSTGRES_DB=marketplace-payment'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5452:5432'
    volumes:
      - postgres:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres:
  postgres_data:
