server:
  servlet:
    context-path: /marketplace
  shutdown: graceful

spring:
  main:
    lazy-initialization: true
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://postgres:5452/marketplace-payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      pool-name: HikariCP
      max-lifetime: 1200000
      connection-timeout: 20000
      auto-commit: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: validate

app:
  chip-collect:
    url: https://gate.chip-in.asia/api/v1
    api-key: